# -*- coding: utf-8 -*-
"""mychatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hAgEboJzXyNOa-44J4zBf9PCM5ZWxfC
"""

!pip install streamlit
!pip install langchain_ollama
import os
import streamlit as st
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_ollama import OllamaLLM

prompt=ChatPromptTemplate.from_messages(
    [
        ("system","You are a helpful assistant. Please respond to the question asked"),
        ("user","Question:{question}")
    ]
)

st.title("Langchain demo with Gemma model")
input_text=st.text_input("What question you have in mind?")

llm = OllamaLLM(model="gemma2:2b")

output_parser=StrOutputParser()
chain=prompt|llm|output_parser

st.write(chain.invoke({"question":input_text}))

"""To resolve the `ConnectError`, we need to set up and run the Ollama server directly within the Colab environment. This involves downloading the Ollama binary, making it executable, starting the server, and then pulling the required `gemma2:2b` model."""

# Install zstd for Ollama extraction
!apt-get install zstd -y

# Download the Ollama binary
!curl -fsSL https://ollama.com/install.sh | sh

# Run Ollama server in the background using nohup
import subprocess
import os

# Start Ollama server with nohup to keep it running in the background
# Redirect output to a log file to avoid blocking the kernel
subprocess.Popen(["nohup", "ollama", "serve"], stdout=open("ollama_server.log", "w"), stderr=open("ollama_server_error.log", "w"), preexec_fn=os.setpgrp)

# Wait a bit for the server to start
import time
time.sleep(10) # Increased sleep time for server to fully initialize

print("Ollama server started (hopefully).")
print("Check ollama_server.log and ollama_server_error.log for status.")

# Pull the gemma2:2b model
!ollama pull gemma2:2b

print("Gemma2:2b model pulled.")

"""Now that the Ollama server is running and the `gemma2:2b` model is downloaded, you can re-run the cell with the `OllamaLLM` initialization and the Streamlit app logic."""